#!/usr/bin/env bash
# scripts that Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
REDIRECT="  location /redirect_me {\nreturn 301 permanent;\n    }"

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

sed -i "48i\ $REDIRECT" /etc/nginx/sites-available/default

NOT_FOUND="error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "47i\ $NOT_FOUND" /etc/nginx/sites-available/default
service nginx start
