#!/usr/bin/env bash
# configuration script for web02 server

apt update
apt install nginx -y
export HOSTNAME=$HOSTNAME
sed -i '57i\add_header X-Served-By $HOSTNAME always;' /etc/nginx/nginx.conf 
/etc/init.d/nginx reload
# sudo service nginx start
