#!/usr/bin/env bash
# script that configures haproxy on a load balancer
sudo apt update -y 
sudo apt-get install --no-install-recommends software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y 
sudo apt-get install haproxy=2.0.\* -y 
sudo chown  $USER:$USER /etc/haproxy/haproxy.cfg
echo "
frontend myfrontend
    bind *:80
    mode http
    default_backend app
backend app
    balance roundrobin
    server 530985-web-01 54.237.209.252:80 check
    server 530985-web-02 52.91.147.218:80 check" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart

