#!/usr/bin/env bash
# scipt to make fix nginx and make it work on port 80
sudo ln -sf /etc/nginx/sites-available/* /etc/nginx/sites-enabled/
echo '' | sudo dd status=none  of=/run/nginx.pid
sudo service nginx restart
