#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100.

limit=100
start=1
for((i=start; i < limit ; i++)); do
    if (( i % 3 == 0 )) && (( i % 5 == 0 )); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
