#!/usr/bin/env bash
#Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

iterations=10
i=0

while [ "$i" -ne "$iterations" ]
do
    if [ "$i" -eq "8" ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School" 
    fi
    ((i++))
done
