#!/usr/bin/env bash
iterations=10
i=0

while [ "$i" -ne "$iterations" ]
do
    if [ "$i" -eq "3" ]; then
        echo "bad luck"
    elif [ "$i" -eq "7" ]; then
        echo "good luck"
    else
        echo "Best School" 
    fi
    ((i++))
done
