#!/bin/bash
iterations=20
i=1

while [ "$i" -le "$iterations" ]
do
    case $i in
        4)
           echo "bad luck from China"
           ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    ((i++))
done
